# Production-specific resource adjustments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axonote-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DEBUG
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axonote-web
spec:
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axonote-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: "1"
          limits:
            memory: "16Gi"
            cpu: "8000m"
            nvidia.com/gpu: "1"
        command: ["celery", "worker", "-A", "app.workers.celery_app", "--loglevel=info", "--concurrency=4", "--optimization=fair"]
