apiVersion: apps/v1
kind: Deployment
metadata:
  name: axonote-web
  namespace: axonote
  labels:
    app: axonote-web
    component: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: axonote-web
  template:
    metadata:
      labels:
        app: axonote-web
        component: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: web
        image: ghcr.io/axonote/axonote-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.axonote.com/api/v1"
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: axonote-web-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: cache
          mountPath: /.next/cache
        - name: temp
          mountPath: /tmp
      volumes:
      - name: cache
        emptyDir: {}
      - name: temp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: axonote-web-service
  namespace: axonote
  labels:
    app: axonote-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: axonote-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: axonote-web-config
  namespace: axonote
data:
  NEXT_PUBLIC_APP_NAME: "AxoNote"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
  NEXT_PUBLIC_ENVIRONMENT: "production"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: axonote-web-hpa
  namespace: axonote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: axonote-web
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
